### ISSUE TITLE
Connecting a WebRequestHandlerHead to the bidi router

### ISSUE THREAD

**Issue by tvanhens** [juxt/modular#18]
Forgive me if this is a stupid question, but how would one connect a WebRequestHandlerHead to the bidi router? 

I have made a WebService component that has some routes that require edn-params middleware and a handle on datomic db that requires a db-uri ring binding. All of these are joined together in a WebRequestHandlerHead and I want to connect this to another section of my application using a common bidi router. It doesn't throw an error when I include it in the using map, however, the route is not accessible on the http server.

**Comment by tangrammer** [comment]
Hi Tyler,
The modular.ring/[WebRequestHandlerHead](https://github.com/juxt/modular/blob/master/modules/ring/src/modular/ring.clj#L50-L51) only implements modular.ring/[WebRequestHandler](https://github.com/juxt/modular/blob/master/modules/ring/src/modular/ring.clj#L10-L14) so you can only connect this component to a modular.http-kit/[WebServer](https://github.com/juxt/modular/blob/master/modules/http-kit/src/modular/http_kit.clj#L13-L16).

On the other hand, modular.bidi/[Router](https://github.com/juxt/modular/blob/master/modules/bidi/src/modular/bidi.clj#L128-L133) only accepts modular.bidi/[WebService](https://github.com/juxt/modular/blob/master/modules/bidi/src/modular/bidi.clj#L17-L23)s


Hope that helps 
Juan

**Comment by tvanhens** [comment]
I think I got the pattern. I used WebRequestHandlerHead as an included webhandler in my WebService component and then served WebService component on the router without problem.

**Comment by tangrammer** [comment]
Although I've never used before WebRequestHandlerHead,  I'll try to write here a few words to explain how I would do it

Following the [doc](https://github.com/juxt/modular/blob/master/modules/ring/src/modular/ring.clj#L41-L48) and the code, using a modular.ring/WebRequestHandlerHead lets you apply WebRequestBindings and WebRequestMiddleware to another modular.ring/WebRequestHandler (delegate) implemented perhaps by a modular.bidi/Router.

So, your system could look like:
```
:webservice-1 (webservice1-fn-constructor ...)
:webservice-2 (webservice2-fn-constructor ...)
:webservice-3 (webservice3-fn-constructor ...)
:current-router (-> (your-current-router-fn-constructor)
                    (using [:webservice-1 :webservice-2 :webservice-3]))
:web-request-middleware (your-middleware-fn-constructor ....)
:web-request-handler-head (-> (your-w-r-h-h-fn-constructor ...) 
                              (using {:request-handler :current-router 
                                      :middleware :web-request-middleware}))
:web-server (-> (your-webserver-fn-constructor)
                   (using {:request-handler :web-request-handler-head}))
 ```
