### ISSUE TITLE
modular.datomic/DatomicConnection doesn't return this on component/start

### ISSUE THREAD

**Issue by tangrammer** [juxt/modular#19]
Hi modular folks, 
Just asking here if there is any reason (besides apparently ease to get the connection in one step call) to differentiate this datomic component [returning](https://github.com/juxt/modular/blob/master/modules/datomic/src/modular/datomic.clj#L44) something different to `this`, in relation other components in modular and stuartsierra/component examples that return `this`

I received an [issue](https://github.com/milesian/BigBang/issues/1) related with this code and only I'm curious about

thanks!

Update:
returning something that doesn't implement IObj limits our app to not use metadata with the related component

**Comment by ordnungswidrig** [comment]
That's a bug in modular, not only that you get something unexpected back, you also cannot `stop` that instance.

**Comment by tangrammer** [comment]
Hi @ordnungswidrig 
I don't think this implementation is a bug because following stuartsierra/component README it seems that "returning something different from `this`" is allowed . Also, you can have components that don't need to be stopped even to implement `component/Lifecycle` 
> Components which do not need lifecycle can be ordinary Clojure maps

In the specific case of DatomicConnection, we don't need to stop this connection instance [either](https://groups.google.com/forum/#!msg/datomic/U-UeG3ocMwQ/kOtZxRXsdfkJ) 

I think that the only weird thing here is the different pattern used in this case in relation with the rest of modular components

**Comment by ordnungswidrig** [comment]
To my understanding everybody expects a component to be restartable, i.e. `(-> comp start stop start)` should work. So while not required by the component library, is seems to be good style.

**Comment by ordnungswidrig** [comment]
Hi @tangrammer you're right regarding datomic connection. This questions the necessity of a "DatomicConnection" component, which can be replaced by a call to `d/connect` with a configured database url.

**Comment by tangrammer** [comment]
Yep! Good explanation

**Comment by tangrammer** [comment]
Fixed on https://github.com/juxt/modular/pull/20
