### ISSUE TITLE
docs are unavailable

### ISSUE THREAD

**Issue by ivar** [juxt/modular#27]
I'm not sure if this is the best place to call attention, but several of the links on the [modularity.org](http://modularity.org) website are broken including http://modularity.org/docs.html and http://modularity.org/book/index.html .

**Comment by malcolmsparks** [comment]
It's as good a place as any :)

Thanks for the issue, which I've now fixed.

The problem was simple - I'd moved the site over to a new server, but hadn't git cloned local repos of the source markdown content from which the docs and book are generated.
